package tech.stonks.drinkbar.composeui.drinkdetails.mapper

import tech.stonks.drinkbar.xml_ui.navigation.mapper.DestinationPresentationToUiMapper

interface DrinkDetailsDestinationToUiMapper : DestinationPresentationToUiMapper